export const skillCatalog = [
  { name: "Python", category: "Programming", aliases: ["py", "pyt", "python programming"] },
  { name: "JavaScript", category: "Programming", aliases: ["js", "javascript programming"] },
  { name: "TypeScript", category: "Programming", aliases: ["ts"] },
  { name: "Java", category: "Programming", aliases: ["java programming"] },
  { name: "PHP", category: "Programming", aliases: ["php programming"] },
  { name: "Go", category: "Programming", aliases: ["golang"] },
  { name: "C", category: "Programming", aliases: ["c programming"] },
  { name: "C++", category: "Programming", aliases: ["cpp", "cplusplus"] },
  { name: "C#", category: "Programming", aliases: ["csharp", "dotnet"] },
  { name: "Ruby", category: "Programming", aliases: ["ruby programming"] },
  { name: "Kotlin", category: "Programming", aliases: ["android kotlin"] },
  { name: "Swift", category: "Programming", aliases: ["ios swift"] },
  { name: "Dart", category: "Programming", aliases: ["flutter dart"] },
  { name: "SQL", category: "Database", aliases: ["structured query language"] },
  { name: "PostgreSQL", category: "Database", aliases: ["postgres", "pgsql"] },
  { name: "MySQL", category: "Database", aliases: ["mysql database"] },
  { name: "MongoDB", category: "Database", aliases: ["mongo", "nosql"] },
  { name: "Redis", category: "Database", aliases: ["redis cache"] },
  { name: "Firebase", category: "Cloud", aliases: ["firebase realtime database", "firestore"] },
  { name: "Supabase", category: "Cloud", aliases: ["supabase postgres"] },
  { name: "React", category: "Frontend", aliases: ["reactjs", "react.js"] },
  { name: "Vue.js", category: "Frontend", aliases: ["vue", "vuejs"] },
  { name: "Angular", category: "Frontend", aliases: ["angular framework"] },
  { name: "Next.js", category: "Frontend", aliases: ["next", "nextjs"] },
  { name: "Vite", category: "Frontend", aliases: ["vitejs"] },
  { name: "Tailwind CSS", category: "Frontend", aliases: ["tailwind", "tailwindcss"] },
  { name: "Bootstrap", category: "Frontend", aliases: ["bootstrap css"] },
  { name: "HTML", category: "Frontend", aliases: ["html5"] },
  { name: "CSS", category: "Frontend", aliases: ["css3"] },
  { name: "Sass", category: "Frontend", aliases: ["scss"] },
  { name: "Node.js", category: "Backend", aliases: ["node", "nodejs"] },
  { name: "Express.js", category: "Backend", aliases: ["express", "expressjs"] },
  { name: "NestJS", category: "Backend", aliases: ["nestjs", "nest"] },
  { name: "Laravel", category: "Backend", aliases: ["php laravel"] },
  { name: "Django", category: "Backend", aliases: ["python django"] },
  { name: "Flask", category: "Backend", aliases: ["python flask"] },
  { name: "FastAPI", category: "Backend", aliases: ["python fastapi"] },
  { name: "REST API", category: "Backend", aliases: ["rest", "restful", "restful api"] },
  { name: "GraphQL", category: "Backend", aliases: ["graphql api"] },
  { name: "JWT", category: "Security", aliases: ["json web token", "auth token"] },
  { name: "OAuth", category: "Security", aliases: ["oauth2", "oauth 2.0"] },
  { name: "Git", category: "Tools", aliases: ["version control"] },
  { name: "GitHub", category: "Tools", aliases: ["github actions", "git hub"] },
  { name: "GitLab", category: "Tools", aliases: ["gitlab ci", "git lab"] },
  { name: "Docker", category: "DevOps", aliases: ["container", "containers"] },
  { name: "Kubernetes", category: "DevOps", aliases: ["k8s"] },
  { name: "CI/CD", category: "DevOps", aliases: ["continuous integration", "continuous deployment"] },
  { name: "Linux", category: "DevOps", aliases: ["linux server"] },
  { name: "Nginx", category: "DevOps", aliases: ["nginx web server"] },
  { name: "AWS", category: "Cloud", aliases: ["amazon web services"] },
  { name: "Google Cloud Platform", category: "Cloud", aliases: ["gcp", "google cloud"] },
  { name: "Microsoft Azure", category: "Cloud", aliases: ["azure"] },
  { name: "Vercel", category: "Cloud", aliases: ["vercel deployment"] },
  { name: "Netlify", category: "Cloud", aliases: ["netlify deployment"] },
  { name: "Data Analysis", category: "Data", aliases: ["data analytics", "analisis data"] },
  { name: "Data Visualization", category: "Data", aliases: ["visualisasi data", "dataviz"] },
  { name: "Data Cleaning", category: "Data", aliases: ["data cleansing", "data wrangling"] },
  { name: "Data Wrangling", category: "Data", aliases: ["data cleaning"] },
  { name: "Exploratory Data Analysis", category: "Data", aliases: ["eda"] },
  { name: "Statistics", category: "Data", aliases: ["statistik"] },
  { name: "Excel", category: "Data", aliases: ["microsoft excel", "spreadsheet"] },
  { name: "Tableau", category: "Data", aliases: ["tableau dashboard"] },
  { name: "Power BI", category: "Data", aliases: ["powerbi", "bi dashboard"] },
  { name: "Looker Studio", category: "Data", aliases: ["google data studio", "looker"] },
  { name: "Pandas", category: "Data", aliases: ["python pandas"] },
  { name: "NumPy", category: "Data", aliases: ["numpy python"] },
  { name: "Matplotlib", category: "Data", aliases: ["python matplotlib"] },
  { name: "Seaborn", category: "Data", aliases: ["python seaborn"] },
  { name: "Plotly", category: "Data", aliases: ["plotly dash"] },
  { name: "Machine Learning", category: "AI", aliases: ["ml"] },
  { name: "Deep Learning", category: "AI", aliases: ["dl"] },
  { name: "Natural Language Processing", category: "AI", aliases: ["nlp"] },
  { name: "Computer Vision", category: "AI", aliases: ["cv"] },
  { name: "TensorFlow", category: "AI", aliases: ["tensorflow keras", "tf"] },
  { name: "Keras", category: "AI", aliases: ["tensorflow keras"] },
  { name: "PyTorch", category: "AI", aliases: ["torch"] },
  { name: "Scikit-learn", category: "AI", aliases: ["sklearn", "sci kit learn"] },
  { name: "XGBoost", category: "AI", aliases: ["xgboost model"] },
  { name: "LightGBM", category: "AI", aliases: ["light gbm"] },
  { name: "spaCy", category: "AI", aliases: ["spacy nlp"] },
  { name: "NLTK", category: "AI", aliases: ["nltk python"] },
  { name: "Transformers", category: "AI", aliases: ["hugging face", "huggingface"] },
  { name: "Prompt Engineering", category: "AI", aliases: ["prompting"] },
  { name: "UI Design", category: "Design", aliases: ["user interface design"] },
  { name: "UX Design", category: "Design", aliases: ["user experience design"] },
  { name: "Figma", category: "Design", aliases: ["figma design"] },
  { name: "Wireframing", category: "Design", aliases: ["wireframe"] },
  { name: "Prototyping", category: "Design", aliases: ["prototype"] },
  { name: "User Research", category: "Design", aliases: ["ux research"] },
  { name: "Project Management", category: "Business", aliases: ["manajemen proyek"] },
  { name: "Agile", category: "Business", aliases: ["agile methodology"] },
  { name: "Scrum", category: "Business", aliases: ["scrum methodology"] },
  { name: "Product Management", category: "Business", aliases: ["product manager"] },
  { name: "Business Analysis", category: "Business", aliases: ["business analyst"] },
  { name: "Digital Marketing", category: "Marketing", aliases: ["marketing digital"] },
  { name: "SEO", category: "Marketing", aliases: ["search engine optimization"] },
  { name: "Content Marketing", category: "Marketing", aliases: ["content strategy"] },
  { name: "Social Media Marketing", category: "Marketing", aliases: ["smm"] },
  { name: "Communication", category: "Soft Skill", aliases: ["komunikasi"] },
  { name: "Teamwork", category: "Soft Skill", aliases: ["collaboration", "kolaborasi"] },
  { name: "Leadership", category: "Soft Skill", aliases: ["kepemimpinan"] },
  { name: "Problem Solving", category: "Soft Skill", aliases: ["problem-solving", "pemecahan masalah"] },
  { name: "Critical Thinking", category: "Soft Skill", aliases: ["berpikir kritis"] },
  { name: "Time Management", category: "Soft Skill", aliases: ["manajemen waktu"] },
  { name: "Adaptability", category: "Soft Skill", aliases: ["adaptasi"] },
  { name: "Public Speaking", category: "Soft Skill", aliases: ["presentation", "presentasi"] },
];
